### ISSUE TITLE
Greek language is not added

### ISSUE THREAD

**Issue by armenistis** [Stremio/stremio-translations#304]
I've made Greek translation some months ago but never added to the app.

**Comment by Ivshti** [comment]
we will check this right away, seems like a bug on our end

**Comment by core1024** [comment]
Fixed in https://github.com/Stremio/stremio-translations/pull/305

**Comment by armenistis** [comment]
in Windows is ok but in android app Greek translation still not working
